networks:
  docker-network:
    name: docker-network
    driver: bridge

volumes:
  postgres_data:
    name: url_shortener_data

services:
  db:
    image: postgres:16-alpine
    container_name: url_shortener_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 3s
      timeout: 3s
      retries: 10
    networks:
      - docker-network

  api:
    container_name: url_shortener_api
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/url_shortener
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./alembic/:/app/alembic/
      - ./alembic.ini:/app/alembic.ini
    networks:
      - docker-network
